import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "IN | Website Travel",
  description: "Generated by RUI Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
    
    <link rel="shortcut icon" href="logo.svg" type="image/x-icon"/>
</head>
      <body >
       {children}
      
        </body>
       
    </html>
  );
}
